### ISSUE TITLE
Different characters, same speaker tag

### ISSUE THREAD

**Issue by lucagiovannini7** [dracor-org/epdracor-whois#1]
@cmil How do we deal with different characters which share the same in-text `<speaker>` tag?

Take as an example [this play](https://texts.earlyprint.org/works/A08360.xml). There are two different Messengers, which are both marked in text as "Nuntius", but the one speaking [here ](https://texts.earlyprint.org/works/A08360.xml?page=023-a) is not the same speaking [here](https://texts.earlyprint.org/works/A08360.xml?page=035-a). 

Thanks to the who-is tool. I can create a nuntius_1 and nuntius_2 for the `particDesc`, but seemingly there's no way of linking the right speech instances to each one. Here the issue is fairly limited and one may tweak the original EP .xml file, but I'm sure that in other plays there's more of these profession-defined characters (servants, messengers, soldiers etc.) which share the same in-text `<speaker>` tags.

**Comment by cmil** [comment]
Good point. That's one of the limitations the tool has at the moment. We could perhaps solve this by providing an interface that allows to assign an ID to each speech individually where there is now just the expandable list of linked speech IDs. 

It could be helpful to collect a few more examples where this would be needed before actually implementing it.

For the above example I would suggest to create a preliminary JSON with nuntius_1 and nuntius_2 in the particDesc and assign one of these IDs to the "Nuntius" speeches. After downloading the JSON I would manually correct the speaker ID for the one speech where it has not been assigned appropriately. I don't think this would need any modification in the source XML files unless there is also some mistake in tagging the text.

**Comment by lucagiovannini7** [comment]
Good solution, thanks, I'll try it out! The same problem concerns collective speaker ids as "both" or "all" (like in [this play](https://texts.earlyprint.org/works/A01353.xml)).
